import classnames from "classnames/bind";
import styles from "./layout.module.scss";
import Header from "./components/organisms/header";
import { Josefin_Sans} from "next/font/google";
import Contact from './components/organisms/contact/index';

const josefinSans = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const ss = classnames.bind(styles);
export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={josefinSans.className}>
      <body>
        <div className={ss("wrapper")}>
          <Contact/>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
